version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    volumes:
      - ./app       # Mount source code
      - ./bot.db:/app/bot.db  # SQLite DB persistence
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
